KDIR   ?= ../../linux-2.6.32.11
PWD    := $(shell pwd)
PATCH  := ../patch_init_offset.py
KO_HDR := ../source/midi_inject_ko.h

all:
	$(MAKE) -C $(KDIR) M=$(PWD) modules
	python3 $(PATCH) midi_inject.ko
	xxd -i midi_inject.ko $(KO_HDR)

clean:
	$(MAKE) -C $(KDIR) M=$(PWD) clean
	rm -f $(KO_HDR)
