KDIR   ?= ../../share/linux-2.6.32.11
PWD    := $(shell pwd)
PATCH  := patch_module.py

all:
	$(MAKE) -C $(KDIR) M=$(PWD) modules
	python3 $(PATCH) dummy_hcd.ko
	python3 $(PATCH) vusb_midi.ko

clean:
	$(MAKE) -C $(KDIR) M=$(PWD) clean
