#!/usr/bin/env python3
"""Generate source/lit_detect_refs.h - the Nautilus MODE/PAGE popup templates
used by screenremote.c's lit_state().

Inputs are the native 1:1 crops in tools/lit_refs/ (RGB565 framebuffer pixels
expanded to RGB888, so the conversion back is exact). Each file name carries
the crop's screen origin: <name>_native_x<X>_y<Y>.png.

A template is a set of sample points, each tagged with a class. A class is one
exact pixel value in the reference crop; only "solid" pixels (at least two of
the pixel's 4 neighbours share its value) are used, so anti-aliased glyph
edges never become sample points. The daemon matches on equality relations only -
points of one class must share a value, different classes must differ - so
the actual colours are never compared.

Usage: python3 tools/gen_lit_refs.py [--check fb.raw ...]
  --check scores each template against raw 800-wide RGB565 framebuffer dumps
  (dd if=/dev/fb1 bs=1600 count=480) and against the upscaled client
  screenshots in mode_page_hook_module/, using the same rule as the daemon.
"""
import argparse
import os
import re
import sys
from collections import defaultdict

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REF_DIR = os.path.join(ROOT, "tools", "lit_refs")
OUT = os.path.join(ROOT, "source", "lit_detect_refs.h")

SOLID_NEIGHBOURS = 2   # same-valued 4-neighbours a pixel needs to be sampled
MIN_CLASS_PX = 12      # solid pixels a value needs to become a class
MAX_CLASSES = 2        # background + glyph
MAX_PER_CLASS = 48     # sample points kept per class
BG_MARGIN = 3          # points are taken only this close to the glyph

# name -> (reference crop, glyph bounding box in crop coordinates x0,y0,x1,y1)
TEMPLATES = {
    "close_x": ("closeX_native_x722_y0.png", None),
    "mode_ul": ("modeUL_native_x0_y0.png", (12, 18, 75, 37)),
}


def to565(p):
    r, g, b = p[:3]
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def load_crop(fname):
    m = re.search(r"_x(\d+)_y(\d+)\.png$", fname)
    ox, oy = int(m.group(1)), int(m.group(2))
    im = Image.open(os.path.join(REF_DIR, fname)).convert("RGB")
    w, h = im.size
    px = im.load()
    return ox, oy, w, h, [[to565(px[x, y]) for x in range(w)] for y in range(h)]


def build(fname, glyph_box):
    ox, oy, w, h, g = load_crop(fname)
    solid = defaultdict(list)
    for y in range(h):
        for x in range(w):
            v = g[y][x]
            same = sum(0 <= x + dx < w and 0 <= y + dy < h and g[y + dy][x + dx] == v
                       for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)))
            if same >= SOLID_NEIGHBOURS:
                solid[v].append((x, y))
    by_count = sorted(solid, key=lambda v: -len(solid[v]))
    bg = by_count[0]
    if glyph_box is None:
        # Glyph = every non-background pixel strictly inside the crop's outline.
        pts = [(x, y) for y in range(h) for x in range(w)
               if g[y][x] != bg and 4 < x < w - 5 and 4 < y < h - 5]
        glyph_box = (min(p[0] for p in pts), min(p[1] for p in pts),
                     max(p[0] for p in pts), max(p[1] for p in pts))
    gx0, gy0, gx1, gy1 = glyph_box
    near = {v: [(x, y) for x, y in solid[v]
                if gx0 - BG_MARGIN <= x <= gx1 + BG_MARGIN and
                   gy0 - BG_MARGIN <= y <= gy1 + BG_MARGIN] for v in solid}
    classes = [v for v in sorted(near, key=lambda v: -len(near[v]))
               if len(near[v]) >= MIN_CLASS_PX][:MAX_CLASSES]
    points = []
    for ci, v in enumerate(classes):
        cand = near[v]
        step = max(1, -(-len(cand) // MAX_PER_CLASS))
        for x, y in cand[::step]:
            points.append((ox + x, oy + y, ci))
    return points, classes, (ox, oy, w, h)


def score(points, nclasses, read):
    """Same rule as lit_match() in screenremote.c."""
    ref = []
    for c in range(nclasses):
        cp = [p for p in points if p[2] == c]
        a, b, d = (read(cp[i][0], cp[i][1]) for i in range(3))
        ref.append(a if a in (b, d) else b)
    if len(set(ref)) != nclasses:
        return 0.0
    hits = sum(read(x, y) == ref[c] for x, y, c in points)
    return hits / len(points)


def emit(built):
    out = ["/* Generated by tools/gen_lit_refs.py from tools/lit_refs/ - do not hand-edit.",
           " * Nautilus MODE/PAGE popup templates for lit_state() in screenremote.c:",
           " * absolute 800x480 screen coordinates plus a class id per point. Points of",
           " * one class must share a pixel value and the classes must differ from each",
           " * other; the values themselves are never compared. */",
           "#ifndef LIT_DETECT_REFS_H", "#define LIT_DETECT_REFS_H", "",
           "struct lit_px { uint16_t x, y; uint8_t cls; };", "",
           "#define LIT_MAX_CLASSES %d" % max(len(b[1]) for b in built.values()),
           "/* last screen row either template reads */",
           "#define LIT_BAND_Y1 %d" % max(b[2][1] + b[2][3] - 1 for b in built.values()), ""]
    for name, (points, classes, (ox, oy, w, h)) in built.items():
        out.append("/* %s: region x=%d..%d y=%d..%d, %d classes (reference values %s) */"
                   % (name, ox, ox + w - 1, oy, oy + h - 1, len(classes),
                      " ".join("0x%04x" % v for v in classes)))
        out.append("#define LIT_%s_CLASSES %d" % (name.upper(), len(classes)))
        out.append("#define LIT_%s_X0 %d" % (name.upper(), ox))
        out.append("#define LIT_%s_X1 %d" % (name.upper(), ox + w - 1))
        out.append("#define LIT_%s_Y1 %d" % (name.upper(), oy + h - 1))
        out.append("static const struct lit_px g_lit_%s[] = {" % name)
        row = []
        for x, y, c in points:
            row.append("{%d,%d,%d}," % (x, y, c))
            if len(row) == 8:
                out.append("    " + " ".join(row)); row = []
        if row:
            out.append("    " + " ".join(row))
        out.append("};")
        out.append("")
    out.append("#endif")
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", nargs="*", default=[])
    args = ap.parse_args()
    built = {n: build(f, box) for n, (f, box) in TEMPLATES.items()}
    with open(OUT, "w") as f:
        f.write(emit(built))
    for n, (pts, cls, _) in built.items():
        print("%s: %d points, %d classes" % (n, len(pts), len(cls)))
    if not args.check:
        return

    for path in args.check:
        d = open(path, "rb").read()
        read = lambda x, y, d=d: d[(y * 800 + x) * 2] | d[(y * 800 + x) * 2 + 1] << 8
        print(os.path.basename(path), " ".join(
            "%s=%.3f" % (n, score(p, len(c), read)) for n, (p, c, _) in built.items()))

    # The client screenshots are the same regions upscaled ~2.1x with
    # interpolation, so exact equality can't hold there. Instead label each
    # screenshot pixel with its nearest class colour and report the best
    # agreement over a small scale/offset search.
    shots = {"close_x": "closeX.png", "mode_ul": "modeUL.png"}
    for n, (pts, cls, (ox, oy, w, h)) in built.items():
        im = Image.open(os.path.join(ROOT, "mode_page_hook_module", shots[n])).convert("RGB")
        sw, sh = im.size
        px = im.load()
        cols = [((v >> 11) << 3, ((v >> 5) & 63) << 2, (v & 31) << 3) for v in cls]
        best = (0, 0, 0, 0)
        for s100 in range(200, 241):
            s = s100 / 100
            for dx in range(-6, 7):
                for dy in range(-6, 7):
                    ok = 0
                    for x, y, c in pts:
                        X, Y = int((x - ox + 0.5) * s) + dx, int((y - oy + 0.5) * s) + dy
                        if 0 <= X < sw and 0 <= Y < sh:
                            p = px[X, Y]
                            d = [sum((p[i] - q[i]) ** 2 for i in range(3)) for q in cols]
                            ok += d.index(min(d)) == c
                    if ok > best[0]:
                        best = (ok, s, dx, dy)
        print("%s vs %s: %.3f (scale %.2f, offset %d,%d)"
              % (n, shots[n], best[0] / len(pts), best[1], best[2], best[3]))


if __name__ == "__main__":
    sys.exit(main())
