#!/usr/bin/env python3
"""
Kronos Cleaner Package Builder

Creates a USB-installable package that removes ALL non-Korg artifacts,
restoring the Kronos as close to factory state as possible without a
full firmware reinstall.

Removes:
  Root hack    — grub init=/bin/init, dropbear SSH, OA.clonos.*, clontab,
                 /bin/init, /bin/login, /etc/profile, /etc/shells, keymaps
  ScreenRemote — /korg/rw/screenremote/, logs, kronosmods_init, kronos_init,
                 grub init=/korg/kronos_init, KronosMods Boot grub entry,
                 OA.clonos.rc injection
  Extraction   — KronosExtract.bin, chip_sniff_ring.bin, kronos_extract.ko

Does NOT remove (a Korg firmware reinstall restores these):
  /sbin/busybox — factory Kronos may ship its own version; harmless to leave

Safety:
  Boot-critical files (/bin/init, /etc/clontab, etc.) are only removed
  AFTER verifying grub.conf no longer references init=/bin/init.

Usage:
    python build_cleaner.py [version]
"""

import shutil
import sys
import tarfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from build_package import (
    _make_pretar, _sha1_signature, _md5_file,
    _MD5SUM_PAYLOAD_REL, _DISPLAY_MSG_PAYLOAD_REL,
    GRUB_ENTRY_TITLE,
)

PKG_NAME = "Kronos-Cleaner"
_DUM = "/mnt/updaterSource/DisplayUpdaterMessage"
_MD5 = "/mnt/updaterSource/md5sum"

# Factory grub.conf -- identical in KRONOS_Update_3_2_1 and 3_2_2 tarballs.
# MD5 verified against both .csum files.
FACTORY_GRUB_MD5 = "65e53d65411d3d9312069ca1f7a7ac37"
FACTORY_GRUB_CONF = (
    "# grub.conf generated by anaconda\n"
    "#\n"
    "# Note that you do not have to rerun grub after making changes to this file\n"
    "# NOTICE:  You have a /boot partition.  This means that\n"
    "#          all kernel and initrd paths are relative to /boot/, eg.\n"
    "#          root (hd0,0)\n"
    "#          kernel /vmlinuz-version ro root=/dev/sda2\n"
    "#          initrd /initrd-version.img\n"
    "#boot=/dev/sda\n"
    "default=0\n"
    "timeout=0\n"
    "hiddenmenu\n"
    "\n"
    "title Linux (2.6.32.11)-320m STG 8x6\n"
    "\troot (hd0,0)\n"
    "\tkernel /bzImage root=/dev/sda2 max_loop=16 fbcon=map:0 memmap=384m"
    " vga=0x0303 loglevel=0 fastboot Single raid=noautodetect elevator=noop\n"
    "\n"
)


def _make_cleaner_posttar() -> str:
    diag_dir = "/korg/rw/HD/KronosCleaner"

    lines = [
        "#!/bin/sh",
        f"# posttar.sh -- {PKG_NAME}",
        "",
        f"mkdir -p {diag_dir} 2>/dev/null || true",
        f"echo \"cleaner: started $(date)\" >> {diag_dir}/cleaner_diag.txt 2>/dev/null",
        "",
        "# -- Precondition: factory boot target must exist --",
        "if [ ! -x /sbin/init ] || [ ! -f /etc/inittab ]; then",
        f"    echo 'ABORT: /sbin/init or /etc/inittab missing' >> {diag_dir}/cleaner_diag.txt",
        "    echo 'Error: factory init missing. Clean aborted.' > /tmp/installer_status",
        f"    {_DUM} 'Error: factory init missing. Clean aborted.' 2>/dev/null",
        f"    {_DUM} 'SetDefaultPalette' 2>/dev/null",
        "    echo 'set 100' > /proc/OmapNKS4ProgressBar",
        "    exit 1",
        "fi",
        f"echo 'cleaner: precondition OK (/sbin/init + /etc/inittab)' >> {diag_dir}/cleaner_diag.txt",
        "",
        "# -- Stop non-factory processes and unload modules --",
        "kill $(pidof screenremote) 2>/dev/null || true",
        "kill $(pidof dropbear) 2>/dev/null || true",
        "rmmod vkbd 2>/dev/null || true",
        "rmmod kronos_extract 2>/dev/null || true",
        "",
        f"{_DUM} 'Restoring factory boot...' 2>/dev/null",
        "",
        "# ====================================================================",
        "# GRUB: restore factory grub.conf, validated against Korg .csum MD5",
        "# ====================================================================",
        f"FACTORY_MD5={FACTORY_GRUB_MD5}",
        "",
        "_boot_mounted=0",
        "if mount -t vfat /dev/sda1 /boot 2>/dev/null; then",
        "    _boot_mounted=1",
        f"    echo 'cleaner: mounted sda1 as vfat' >> {diag_dir}/cleaner_diag.txt",
        "elif mount /dev/sda1 /boot 2>/dev/null; then",
        "    _boot_mounted=1",
        f"    echo 'cleaner: mounted sda1 (auto-type)' >> {diag_dir}/cleaner_diag.txt",
        "else",
        f"    echo 'cleaner: WARNING: failed to mount sda1' >> {diag_dir}/cleaner_diag.txt",
        "fi",
        "",
        "GRUB_OK=0",
        "if [ -f /boot/grub/grub.conf ]; then",
        f"    cp /boot/grub/grub.conf {diag_dir}/grub_before_clean.txt 2>/dev/null || true",
        f"    _cur_md5=$({_MD5} /boot/grub/grub.conf 2>/dev/null | awk '{{print $1}}')",
        f"    echo \"cleaner: grub before md5=$_cur_md5\" >> {diag_dir}/cleaner_diag.txt",
        "",
        "    if [ \"$_cur_md5\" = \"$FACTORY_MD5\" ]; then",
        f"        echo 'cleaner: grub.conf already factory' >> {diag_dir}/cleaner_diag.txt",
        "        GRUB_OK=1",
        "    else",
        "        # Write known-good factory grub.conf (from KRONOS_Update_3_2_1/2 tarball)",
        # --- heredoc content: not indented, tabs are literal ---
        "    cat << 'FACTORY_GRUB' > /boot/grub/grub.conf",
        *FACTORY_GRUB_CONF.split("\n")[:-1],
        "FACTORY_GRUB",
        "",
        "        # Ensure menu.lst is a symlink to grub.conf (matches factory tarball)",
        "        rm -f /boot/grub/menu.lst 2>/dev/null",
        "        ln -s ./grub.conf /boot/grub/menu.lst 2>/dev/null || true",
        "",
        "        sync",
        f"        _cur_md5=$({_MD5} /boot/grub/grub.conf 2>/dev/null | awk '{{print $1}}')",
        f"        echo \"cleaner: grub after write md5=$_cur_md5\" >> {diag_dir}/cleaner_diag.txt",
        "",
        "        if [ \"$_cur_md5\" = \"$FACTORY_MD5\" ]; then",
        f"            echo 'cleaner: grub.conf restored to factory (verified)' >> {diag_dir}/cleaner_diag.txt",
        "            GRUB_OK=1",
        "        else",
        "            # Factory write didn't match -- fall back to sed patching",
        f"            echo 'cleaner: factory write md5 mismatch, falling back to sed' >> {diag_dir}/cleaner_diag.txt",
        "            sed -i 's| init=/bin/init||g' /boot/grub/grub.conf 2>/dev/null || true",
        "            sed -i 's| init=/korg/kronos_init||g' /boot/grub/grub.conf 2>/dev/null || true",
        "            sed -i 's| init=/korg/rw/kronos_init||g' /boot/grub/grub.conf 2>/dev/null || true",
        "            sed -i 's/^default.*/default=0/' /boot/grub/grub.conf 2>/dev/null || true",
        f"            if grep -q '{GRUB_ENTRY_TITLE}' /boot/grub/grub.conf 2>/dev/null; then",
        f"                awk 'BEGIN{{skip=0}}/^title {GRUB_ENTRY_TITLE}$/{{skip=1;next}}skip&&/^title /{{skip=0;print;next}}!skip{{print}}' \\",
        "                    /boot/grub/grub.conf > /tmp/_grub_clean \\",
        "                    && mv /tmp/_grub_clean /boot/grub/grub.conf",
        "            fi",
        "            sync",
        "            if ! grep -q 'init=' /boot/grub/grub.conf; then",
        "                GRUB_OK=1",
        f"                echo 'cleaner: grub.conf sed-patched (no init= remains)' >> {diag_dir}/cleaner_diag.txt",
        "            else",
        f"                echo 'cleaner: WARNING: init= still present after fallback' >> {diag_dir}/cleaner_diag.txt",
        "            fi",
        "        fi",
        "    fi",
        "",
        f"    cp /boot/grub/grub.conf {diag_dir}/grub_after_clean.txt 2>/dev/null || true",
        "else",
        f"    echo 'cleaner: WARNING: /boot/grub/grub.conf not found' >> {diag_dir}/cleaner_diag.txt",
        "fi",
        "",
        "[ \"$_boot_mounted\" = '1' ] && umount /boot 2>/dev/null || true",
        "",
        "# ====================================================================",
        "# Remove non-boot-critical files (safe regardless of GRUB state)",
        "# ====================================================================",
        f"{_DUM} 'Removing SSH and tools...' 2>/dev/null",
        "",
        "# Root-hack SSH / tools",
        "rm -f /bin/dropbear",
        "rm -f /bin/dbclient",
        "rm -f /bin/dropbearconvert",
        "rm -f /bin/dropbearkey",
        "rm -f /bin/scp",
        "rm -f /bin/ssh",
        "rm -f /bin/nano",
        "rm -f /bin/login",
        "rm -rf /etc/dropbear",
        "rm -rf /usr/share/keymaps",
        "rm -f /etc/profile",
        "rm -f /etc/shells",
        "rmdir /root 2>/dev/null || true",
        f"echo 'cleaner: SSH and tools removed' >> {diag_dir}/cleaner_diag.txt",
        "",
        "# ====================================================================",
        "# Remove boot-critical files ONLY if GRUB is confirmed safe",
        "# ====================================================================",
        "if [ \"$GRUB_OK\" = '1' ]; then",
        f"    {_DUM} 'Removing root-hack boot files...' 2>/dev/null",
        "    rm -f /bin/init",
        "    rm -f /etc/OA.clonos.rc",
        "    rm -f /etc/OA.clonos.si",
        "    rm -f /etc/clontab",
        "    rm -f /etc/inittab.busybox",
        f"    echo 'cleaner: boot-critical files removed' >> {diag_dir}/cleaner_diag.txt",
        "else",
        f"    echo 'cleaner: SKIPPED boot-critical removal (GRUB not verified safe)' >> {diag_dir}/cleaner_diag.txt",
        f"    echo 'cleaner: /bin/init, clontab, OA.clonos.* left intact' >> {diag_dir}/cleaner_diag.txt",
        "fi",
        "",
        "# ====================================================================",
        "# Remove ScreenRemote + PackageMaker artifacts",
        "# ====================================================================",
        f"{_DUM} 'Removing ScreenRemote...' 2>/dev/null",
        "",
        "rm -rf /korg/rw/screenremote 2>/dev/null",
        "rm -rf /korg/rw/HD/ScreenRemote 2>/dev/null",
        "rm -f /korg/kronos_init 2>/dev/null",
        "rm -f /korg/rw/kronosmods_init 2>/dev/null",
        "rm -f /korg/rw/.grub_orig_default 2>/dev/null",
        "",
        "# Clean kronosmods injection from OA.clonos.rc (if file was kept)",
        "if [ -f /etc/OA.clonos.rc ] && grep -q 'kronosmods' /etc/OA.clonos.rc 2>/dev/null; then",
        "    awk '!/kronosmods/' /etc/OA.clonos.rc > /tmp/_rc_clean \\",
        "        && mv /tmp/_rc_clean /etc/OA.clonos.rc",
        "    chmod 755 /etc/OA.clonos.rc",
        "fi",
        f"echo 'cleaner: ScreenRemote + PackageMaker artifacts removed' >> {diag_dir}/cleaner_diag.txt",
        "",
        "# ====================================================================",
        "# Remove extraction tool outputs",
        "# ====================================================================",
        "rm -f /korg/rw/KronosExtract.bin 2>/dev/null",
        "rm -f /korg/rw/chip_sniff_ring.bin 2>/dev/null",
        "rm -f /korg/rw/kronos_extract.ko 2>/dev/null",
        f"echo 'cleaner: extraction outputs removed' >> {diag_dir}/cleaner_diag.txt",
        "",
        "# Remove previous unroot diagnostics",
        "rm -rf /korg/rw/HD/Unroot 2>/dev/null",
        "",
        f"echo \"cleaner: done $(date)\" >> {diag_dir}/cleaner_diag.txt",
        f"chown -R 500:500 {diag_dir} 2>/dev/null || true",
        "sync",
        "",
        "# -- Final status --",
        "if [ \"$GRUB_OK\" = '1' ]; then",
        "    echo 'Clean complete. Please reboot.' > /tmp/installer_status",
        f"    {_DUM} 'Clean complete. Please reboot.' 2>/dev/null",
        "else",
        "    echo 'Partial clean: SSH/ScreenRemote removed but boot files kept.' > /tmp/installer_status",
        f"    {_DUM} 'Partial clean. Check diagnostics.' 2>/dev/null",
        "fi",
        f"{_DUM} 'SetDefaultPalette' 2>/dev/null",
        "sync",
        "echo 'set 0' > /proc/OmapNKS4ProgressBar",
        "_p=10",
        "for _i in 1 2 3 4 5 6 7 8 9 10; do",
        "    echo \"set $_p\" > /proc/OmapNKS4ProgressBar",
        "    sleep 1",
        "    _p=$(( _p + 9 ))",
        "done",
        "echo 'set 100' > /proc/OmapNKS4ProgressBar",
        f"{_DUM} 'SetTextPalette' 2>/dev/null",
        "",
        "exit 0",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    version = sys.argv[1] if len(sys.argv) > 1 else "1.0.0"

    print("=" * 52)
    print(f"  {PKG_NAME} Package Builder")
    print("=" * 52)
    print()

    pkg_id = f"{PKG_NAME.replace('-', '_')}_{version.replace('.', '_')}"
    tarball_name = f"{pkg_id}.tar.gz"
    out_dir = Path(__file__).parent / "dist" / pkg_id
    out_dir.mkdir(parents=True, exist_ok=True)

    tarball_path = out_dir / tarball_name
    with tarfile.open(str(tarball_path), "w:gz"):
        pass
    tarball_md5 = _md5_file(tarball_path)

    pretar_text  = _make_pretar(tarball_name, tarball_md5, PKG_NAME)
    posttar_text = _make_cleaner_posttar()
    sig          = _sha1_signature(pretar_text.encode(), posttar_text.encode())

    install_info = (
        f"VERSION={PKG_NAME} {version}\n"
        f"SOURCE={tarball_name}\n"
        f"PRETARSCRIPT=pretar.sh\n"
        f"POSTTARSCRIPT=posttar.sh\n"
        f"SIGNATURE={sig}\n"
    )

    (out_dir / "pretar.sh").write_text(pretar_text,  encoding="ascii", newline="\n")
    (out_dir / "posttar.sh").write_text(posttar_text, encoding="ascii", newline="\n")
    (out_dir / "install.info").write_text(install_info, encoding="ascii", newline="\n")
    (out_dir / "mnt").mkdir(exist_ok=True)

    payload_dir = Path(__file__).parent / "payload"

    md5sum_src = payload_dir.joinpath(*_MD5SUM_PAYLOAD_REL)
    if md5sum_src.is_file():
        shutil.copy2(md5sum_src, out_dir / "md5sum")
        print(f"  md5sum: OK")
    else:
        print(f"  WARNING: md5sum not found at payload/{'/'.join(_MD5SUM_PAYLOAD_REL)}")

    display_msg_src = payload_dir.joinpath(*_DISPLAY_MSG_PAYLOAD_REL)
    if display_msg_src.is_file():
        shutil.copy2(display_msg_src, out_dir / "DisplayUpdaterMessage")
        print(f"  DisplayUpdaterMessage: OK")
    else:
        print(f"  WARNING: DisplayUpdaterMessage not found")

    print()
    print("=" * 52)
    print(f"  Ready: {out_dir}/")
    print("=" * 52)
    print()
    print("Copy to FAT32 USB root:")
    for p in sorted(out_dir.iterdir()):
        note = "  (empty -- required)" if (p.name == "mnt" and p.is_dir()) else ""
        print(f"  {p.name}{note}")
    print()
    print(f"Signature: {sig}")
    print()
    print("Removes:")
    print("  Root hack  — grub init=/bin/init, dropbear, SSH tools, OA.clonos.*,")
    print("               clontab, /bin/init, /bin/login, /etc/profile, /etc/shells")
    print("  ScreenRemote — /korg/rw/screenremote/, logs, kronosmods_init,")
    print("               kronos_init, grub hooks, OA.clonos.rc injection")
    print("  Extraction — KronosExtract.bin, chip_sniff_ring.bin, kronos_extract.ko")
    print()
    print("Safety:")
    print("  Boot-critical files only removed after GRUB verified safe.")
    print("  /sbin/busybox left intact (may be factory; Korg update restores it).")
    print()
    print("Diagnostics: /korg/rw/HD/KronosCleaner/cleaner_diag.txt (FTP-accessible)")
    print()
    print("After install, reboot the Kronos to restore factory boot.")


if __name__ == "__main__":
    main()
